# Generated by Django 3.2.8 on 2021-10-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('idnp', models.IntegerField(max_length=13, verbose_name='idnp')),
                ('fio', models.CharField(max_length=255)),
                ('birthday', models.DateTimeField(verbose_name='birthday')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('tested_at', models.DateTimeField(verbose_name='tested_at')),
                ('laborant_name', models.CharField(max_length=255)),
                ('valid_to', models.DateTimeField(verbose_name='valid_to')),
                ('igG', models.IntegerField(default=0)),
                ('igM', models.IntegerField(default=0)),
                ('igA', models.IntegerField(default=0)),
                ('url_qr_pics', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
        ),
    ]
